# Generated by Django 6.0.6 on 2026-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=500)),
                ('autore', models.CharField(max_length=200)),
                ('editore', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('disponibile', models.BooleanField(default=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('anno_pubblicazione', models.DateField(blank=True)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prodotti',
                'ordering': ['creato_il'],
            },
        ),
    ]
