# Generated by Django 6.0.6 on 2026-06-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='creato_il',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='descrizione',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='editore',
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='prezzo',
        ),
    ]
