# Generated by Django 6.0.5 on 2026-06-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Prodotto',
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['creato_il'], 'verbose_name_plural': 'Libri'},
        ),
    ]
