# Generated by Django 6.0.5 on 2026-06-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_libro_prodotto_alter_prodotto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodotto',
            options={'ordering': ['creato_il'], 'verbose_name_plural': 'Prodotti'},
        ),
    ]
