# Generated by Django 6.0.6 on 2026-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_prodotto_options_remove_prodotto_creato_il_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='anno_pubblicazione',
            field=models.IntegerField(),
        ),
    ]
