# Generated by Django 6.0.6 on 2026-06-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_prodotto_anno_pubblicazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Prodotto_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=200)),
                ('quantita', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Prodotti_new',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienti', to='catalogo.cliente')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prodotti', to='catalogo.prodotto_new')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='ordini',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='catalogo.ordine'),
        ),
    ]
