# Generated by Django 6.0.6 on 2026-06-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_cliente_prodotto_new_ordine_cliente_ordini'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cognome',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='indirizzo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ordine',
            name='data_ordine',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='quantita',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ordine',
            name='stato',
            field=models.CharField(choices=[('in_elaborazione', 'In elaborazione'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('cancellato', 'Cancellato')], default='in_elaborazione', max_length=50),
        ),
        migrations.AddField(
            model_name='ordine',
            name='totale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini_clienti', to='catalogo.cliente'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini_prodotti', to='catalogo.prodotto_new'),
        ),
    ]
