# Generated by Django 6.0.6 on 2026-06-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_cliente_cognome_cliente_email_cliente_indirizzo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ordini',
        ),
    ]
