# Generated by Django 6.0.6 on 2026-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_cliente_ordini'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodotto',
            new_name='Libro',
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libri'},
        ),
        migrations.AlterModelTable(
            name='libro',
            table='libri_prodotto',
        ),
    ]
