# Generated by Django 6.0.6 on 2026-06-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_rename_prodotto_libro_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodotto_new',
            new_name='Prodotto',
        ),
        migrations.AlterModelOptions(
            name='prodotto',
            options={'verbose_name_plural': 'Prodotti'},
        ),
        migrations.AlterModelTable(
            name='prodotto',
            table='prodotti_prodotto_new',
        ),
    ]
