# Generated by Django 6.0.6 on 2026-06-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_rename_prodotto_new_prodotto_alter_prodotto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordine',
            options={'verbose_name_plural': 'Ordini'},
        ),
    ]
